# Generated by Django 2.2 on 2021-09-04 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0002_auto_20210904_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='author_adv',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='advertisements_app.Author'),
        ),
    ]
