# Generated by Django 2.2 on 2021-09-04 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0003_auto_20210904_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Наименование:')),
            ],
        ),
        migrations.AddField(
            model_name='advertisement',
            name='rubric_adv',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rubric', to='advertisements_app.Author'),
        ),
    ]
