# Generated by Django 2.2 on 2021-09-05 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0005_auto_20210904_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeAdv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тип объявления:')),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя автора:'),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Наименование:'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='type_adv',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adv_type', to='advertisements_app.TypeAdv'),
        ),
    ]
