# Generated by Django 2.2 on 2021-09-08 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0006_auto_20210905_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='author_adv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='advertisements_app.Author', verbose_name='Автор:'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='rubric_adv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rubric', to='advertisements_app.Rubric', verbose_name='Наименование:'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='type_adv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adv_type', to='advertisements_app.TypeAdv', verbose_name='Тип объявления:'),
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='author',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='typeadv',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
